### ISSUE TITLE
selected / favorite node

### ISSUE THREAD

**Issue by mlp73** [diogofcunha/react-virtualized-tree#42]
Hi!
Great job with the tree viewer.
It is not clear to me how to use the favorite Renderer, or how to handle select at all.
The idea is to provide the tree picker with an array of selected nodes and to manage the change through the states. I see this is what you attempted to show with the Basic demo with the favorite Renderer, but I am not able to find it documented properly.

Do you have a concrete example / code snippet on how to handle select and change?

**Comment by diogofcunha** [comment]
Hi @mlp73.

Thanks for you comments and for exposing this.

**The tree is not very opinionated about those things by design**. During my experience developing this kind of applications it was always clear in my head that different people like to handle this things differently and small differences in the UX can make the tree look less flexible.

**There isn't a Select renderer included in the package**, I can add one in the future but it should be straight forward for you to implement one. Maybe this is something that would make sense to add as an extension to the main package.

Based on the example presented in the public website I will take you step by step on the approach taken:

1. Create a renderer for selection https://github.com/diogofcunha/react-virtualized-tree//blob/master/demo/src/examples/Extensions.js#L13.
  This renderer receives `node`, `children`, `onChange`, `node `represent the node object itself, `children `represents any child components and `onChange` is the way you lift up changes
2. As selection is not included as a default action, an extra handler needs to be added https://github.com/diogofcunha/react-virtualized-tree//blob/master/demo/src/examples/Extensions.js#L80, This is just a map between action types and functions, when you lift up some action using `onChange` described in the previous point, your action type is looked up in this map and the corresponding function executed.
3. Inside your node renderer fire `onChange` whenever it suits your use case (https://github.com/diogofcunha/react-virtualized-tree//blob/master/demo/src/examples/Extensions.js#L25), don't forget to specify the type of action to be picked up by the previous point.

I have plans to improve the examples website and the docs. Will mark this as a point that needs a clear explanation.

**Comment by mishaberman** [comment]
Thanks for the great control @diogofcunha , it is awesome and much faster than TreeBeard :DI implemented a little bit of a simpler solution than what was mentioned above, although I am looking forward to a built in solution. 

Here is what I did to get selected functionality:

1) Add a **selectedNode** state property
```

  state = {
        nodes: [],
        loading: true,
        **selectedNode**: **null**
    }
```

2) Create a nodeSelected handler that sets the state selectedNode to a node that was clicked
```
nodeSelected = (node) => {
        this.setState({selectedNode: node})
        this.props.onSelect(node);
    }
```

3) Add an onClick handler to the Node generator portion of the Tree, and route the selected node to the **nodeSelected** method. Then within the node generator, I have the text of the node switch between a bolded and non-bolded className based on if the currentNode is the same as the state selectedNode. I also added an icon that is only visible if the node is selected.

```
  <Tree nodes={nodes} onChange={this.handleChange}>
                                        {
                                            ({ node, ...rest }) => {
                                                **let amISelected = this.state.selectedNode && node.id === this.state.selectedNode.id;**
                                                return (
                                                    <div onClick={()=> {this.nodeSelected(node)}}>
                                                        <Expandable
                                                            node={node} {...rest}
                                                            iconsClassNameMap={{
                                                                expanded: 'minusIcon',
                                                                collapsed: 'plusIcon'
                                                            }}>
                                                            **<div className={amISelected ? "check" : "hidden"}/>**
                                                            <div className={"icon " + node.type} />
                                                            **<div className={"sheetPickerNode" + (amISelected ? " nodeSelected" : "") }>{node.name}</div>**
                                                        </Expandable>
                                                    </div>
                                                );
                                            }
                                        }
                                    </Tree>
```

**Comment by diogofcunha** [comment]
Thanks for your kind words @mishaberman

That is a nice solution for your use case, the concept behind this library is that you can apply your own logic and manage state as you wish, what you did it's great and I'm really proud it worked for you 😊
