### ISSUE TITLE
scrolling is not working well with your large dataset (and even worse with larger ones)

### ISSUE THREAD

**Issue by wysisoft** [diogofcunha/react-virtualized-tree#62]
is it just me or does the scroll handle on the large dataset not follow the mouse?
https://diogofcunha.github.io/react-virtualized-tree/#/examples/large-collection 

note the the behavior gets better as you scroll from the very top to bottom and back a few times, like its learning something along the way?

on a larger dataset, I have problems where the scroll handle will run up to the top of the tree and flicker whenever I scroll around?

**Comment by diogofcunha** [comment]
Hi @wysisoft. Thanks for reporting.

I can't reproduce that behaviour.

Can you give a few more hints about the platform, browser and maybe cpu power?

**Comment by wysisoft** [comment]
I adapted react-virtualized example of a treeview and its scroll behavior
has been solid.
https://rawgit.com/bvaughn/react-virtualized/master/playground/tree.html

**Comment by diogofcunha** [comment]
Hi @wysisoft.

I finally have some time to do some investigation on this and the issue seems to react-virtualized cell measurer, if a static rowHeight is assigned the problem disappears. I can understand that the problem can be annoying but for such a large dataset it is more performant to have a fixed row height then computing things on the flight.

If you are still annoyed by this the best thing I could do is allow fixed height rows, is that something you would be interested in?
