### ISSUE TITLE
[Question] Is lazy loading supported?

### ISSUE THREAD

**Issue by karangarg45** [diogofcunha/react-virtualized-tree#88]
Just wanted to make sure that is it possible to load more data via an ajax call on expanding a node?

**Comment by VitaliyBoris** [comment]
Yes, it's possible. Just use onChange() in Expandable extension

**Comment by diogofcunha** [comment]
Thanks

@VitaliyBoris is correct, I will probably add a custom renderer soon that will add some slick animation on loading too

**Comment by fuzzykiller** [comment]
I don’t see how `onChange` would help at all, sorry. It does not allow updating a node’s `children` with `selectors.updateNode`. It can only update `state`. This is what `<Expandable>` does.

Theoretically, there’s `selectors.addNode`, but `getExtensions(...).updateTypeHandlers[type] is not a function`. It is simply not implemented. The API is also very counter-intuitive. It is unclear what `parents` are. Probably indices, I guess...?

**Comment by diogofcunha** [comment]
Hey @fuzzykiller, thanks for the feedback.

Expandable triggers `onChange` when someone expands a node, you can totally hook to that event and do whatever you want with it in the first place! You can change your original tree to add new nodes, delete nodes, it doesn't matter, that's a normal thing to do when using react and this API gives you all the flexibility to do so.

If you want you can also use extensions and there is an example of that [in here](https://diogofcunha.github.io/react-virtualized-tree/#/examples/extensions), I have no idea what you're doing to get that error, but is probably not in the docs.

`ADD_NODE` is actually not implemented but what you need in here is to **change the node that is expanded** and add some children to it, this will most likely be an async operation that should not be handled by this package.

About the API being counter-intuitive and parents referring to parent ids is a common. Also FlattenedTree is an internal typed used by the tree to make calculations easy, the best thing you can do is edit the original tree and just supply the final object to the tree and let it figure it out.

**Comment by FilipeCosta06** [comment]
Hello @diogofcunha,

I recently started looking into this component and I'm wondering, given what is being said in this Issue, why isn't this enough to update (add) the children of a node (or any kind of attribute update for that matter, i.e. renaming) ?

```
onChange({
  ...updateNode(
    {
      ...node,
      name: "updated " + node.name,       // <-- but this works though !
      children: response.payload.children
    },
    {expanded: true}), index}); 
```

I realize I could update the whole data source with the correct values but I'm trying to understand what isn't working more that anything (which is why I'm not opening an issue, even though this one is pretty old ^^).

I first assumed you might only be using the node's ID or something but, as you can see in [this sandbox](https://codesandbox.io/s/sleepy-cherry-vb4l1?file=/components/Tree.jsx:2167-2537), the above code is enough to **rename** the node but no new children appear.

To reproduce, you just need to expand the second item from the top ("Folder A - A") and, after 500ms (mocking async API request), you will see its expected state printed in the console. The node's name is properly changed but the children attribute remains empty.
You can double click a node to print it in the console too.

Any explanation would be seriously appreciated ^^ I saw you are planning a full rewrite of this component and wish you luck because, despiste my current issue (that can be worked around easily, as you said, by providing a new/fixed dataset to the tree), I'm seriously loving it!

**Comment by FilipeCosta06** [comment]
Anyway, as I said, this was more a question out of curiosity than anything. I ended up just using the extension feature instead.

I realize there is close to no point in saying this now but:
I also had the `getExtensions(...).updateTypeHandlers[type] is not a function` error but that was due to me writing 
```
        extensions={{
            [TREE_EXTENSIONS.SET_CHILDREN]: this.lazyLoadingChildrenHandler
        }}
```
instead of
```
        extensions={{
          updateTypeHandlers: {
            [TREE_EXTENSIONS.SET_CHILDREN]: this.lazyLoadingChildrenHandler
          }
        }}
```
:kekw:
