### ISSUE TITLE
wow, Is this a real component ?

### ISSUE THREAD

**Issue by yaolei** [diogofcunha/react-virtualized-tree#91]
The demo source such like this:
import Tree from '../../../src/TreeContainer';
import Renderers from '../../../src/renderers';
import {createEntry, constructTree} from '../toolbelt';
import FilteringContainer from '../../../src/FilteringContainer';
import Favorite from '../../../src/renderers/Favorite';
So i have to copy each of those file and then each file have the dependencies file, So i have to go on find file and copy. Is this really demo source ?

**Comment by diogofcunha** [comment]
Hi @yaolei.

toolbelt is a set of helpers on the demo to create data.

There is a usage section on the README, you do not need to copy anything, you just need to use the npm package.

> https://github.com/diogofcunha/react-virtualized-tree#usage

The demo source code is an example that is deployed to the public website, it uses the internal source code because it's a lot of boilerplate to use the npm package itself, having it as a 100% copy paste source was never my priority, that may change in the future if I move the examples to code sandbox but at this stage it's not on my list.
 
The package also has accurate types and any modern source code editor will help you in the imports
